---
title: "Day 1 MBARI Software Carpentry"
author: "Julie"
date: "11/30/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `ggplot` stuff

(I actually didn't do this, but follow along in Ben's repo: <https://bbest.github.io/ds-repo/>)


## Exploring gapminder data

```{r}

library(tidyverse)

gapminder <- readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

gapminder

## useful functions to get to know your data:
head(gapminder) # show the first 6 rows of the data
tail(gapminder) # show the last 6 rows of data

head(gapminder, 10) # say how many!
tail(gapminder, 9)

## check out the structure of your data
str(gapminder)

## column names 
names(gapminder)

## dimensions of the data
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

## combine with c()
c(nrow(gapminder), ncol(gapminder))

## summary statistics
summary(gapminder)

## for everything above, we were operating on the whole gapminder dataset.

head(gapminder$lifeExp)

```

`read_csv` is from the `readr` package (part of the tidyverse). It is not `read.csv`, which is part of base R. 

## Data wrangling with dplyr

## `filter()` by rows
```{r}

filter(gapminder, lifeExp < 29)

filter(gapminder, country == "Mexico")

sweden <- filter(gapminder, country == "Sweden")
mean(sweden$lifeExp)

mean(filter(gapminder, country == "Sweden")$lifeExp)

## pipe operator `%>%` 

## same output!
gapminder %>% head(3)
head(gapminder, 3)

## let's use the %>% with our Sweden example
sweden <- filter(gapminder, country == "Sweden")
x <- mean(sweden$lifeExp)

## getting ahead of ourselves
y <- gapminder %>% 
  filter(country == "Sweden") %>% 
  summarize(mean_lifeExp = mean(lifeExp))

```

## `select()` by columns

```{r}

## select 2 columns
select(gapminder, year, lifeExp)

## with the pipe operator
gapminder %>%
  select(year, lifeExp) %>%
  tail()

## combine what we've learned with the pipe

gapminder %>%
  filter(country == "Cambodia") %>%
  select(country, year, pop, gdpPercap)

## same as above
gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)

## a few more things with `filter()`
gapminder %>%
  filter(country == "Mexico",
         year == 2002)

## `mutate()` to add columns

gapminder %>%
  mutate(gdp = pop * gdpPercap)

## let's add an index
test <- gapminder %>%
  mutate(gdp = pop * gdpPercap, 
         index = 1:nrow(gapminder)) %>%
  tail()

## not the right way, shouldn't work (only returns half)
gapminder %>%
  filter(country == c("Egypt", "Vietnam") )

## `%in%` operator lets you filter multiple things within a `c()`
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam") )

## find the maximum gdpPercap of Egypt and Vietnam, in a new column.
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam") ) %>%
  mutate(max_gdpPercap = max(gdpPercap))


## group_by() so that we can get 2 maxes
gapminder %>%
  filter(country %in% c("Egypt", "Vietnam") ) %>%
  group_by(country) %>%
  # mutate(max_gdpPercap = max(gdpPercap))
  summarize(max_gdpPercap = max(gdpPercap))
```

## `group_by()` and `summarize()`

```{r, eval=FALSE}

gapminder %>%
  group_by(country) %>%
  summarize(max_gdpPercap = max(gdpPercap))

## let's keep the year associated with that max_gdpPercap
gapminder %>%
  group_by(country) %>%
  mutate(max_gdpPercap = max(gdpPercap)) %>%
  filter(max_gdpPercap == gdpPercap) %>%
  arrange(max_gdpPercap) # if you wanted descending order, arrange(desc(max_gdpPercap))

```

## joining datasets
```{r}
## read in CO2 emmissions data
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

co2 %>% head()
co2 %>% str() # 12 rows

## crate new variable with only gapminder 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007)
gap_2007 %>% head()
gap_2007 %>% str() # 142 rows

## left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")
lj %>% dim() # 142 rows
# lj %>% View()

## right_join gap_2007 to co2
rj <- right_join(gap_2007, co2)
rj %>% dim() # 12
# rj %>% View()
```





